### PR TITLE
Add AWS support

### PR DESCRIPTION
**Pull request by jokebroker**
Hi - have added preliminary AWS support :)

### CODE REVIEW

**Comment by jokebroker** [comment]
Managed to break the api - will review in the .au AM

**Comment by deckarep** [comment]
@jokebroker I fully expected the API to break since the original implementation was a bit bias to DigitalOcean as that is what was the original implementation as you know.

With that said, this is already looking great and I’m super excited to have AWS instances available for this.

Let me know when you’re ready for a review.

Thanks for the contribution!

**Comment by jokebroker** [comment]
Okay, should be ready for review now. 

Some fmt/imports cleaning & added corresponding field/method to DoSpinSettings, leaving additional generalisation of the API till perhaps after GCE support goes in.

**Comment by deckarep** [comment]
Sorry for the delay on this...looks good to me.  Thanks for the contribution!

I'll likely follow-up up with some small refactoring in the future with the DO and AWS code to clean up a few things.

**Pull request merged**
